### ISSUE TITLE
Metadatas are not allowed during the device provisioning

### ISSUE THREAD

**Issue by ralcaide** [telefonicaid/fiware-IoTAgent-Cplusplus#165]
Hello,

I'm trying to create a device with attributes that contains metadatas as follow:
{
 "devices": [
    { "device_id": "DEV_ID",
      "entity_name": "ENTITY_ID",
      "entity_type": "thing",
      "timezone": "Europe/Madrid",
"attributes": [
        { "object_id": "t",
          "name": "temperature",
          "type": "int",
          "metadatas": [
           {
            "name" : "unit",
            "type" : "string",
            "value" : "celsius"
           }
          ]
        } ],
 "static_attributes": [
        { "name": "att_name",
          "type": "string",
          "value": "value"
        }
       ]
      }
     ]
    } 

But I got and invalid response and the Entity is not created:
- Status Code: 400
- Response: 
  {"reason":"The request is not well formed","details":"Additional properties not allowed. [/devices[0]/attributes[0]/metadatas]"}

I'm using the FIGWAY code to do that, the command registerDevice.py
IDAS: 130.206.80.40:5371
ORION: 130.206.80.40:1026

It is that normal? The metadatas should be supported by the IoT Agent, isn't?

**Comment by agonlucas** [comment]
In release/1.0.1 branch, metadatas are not supported en provisioning API. We are agreed metadatas should be supported. We are going to work in this feature.

**Comment by ralcaide** [comment]
Thanks a lot,

please, keep me informed.

**Comment by agonlucas** [comment]
In develop (1.2.0) you can assign metadatas to "attributes" and "static_attributes" fields. This version is unstable.
