### ISSUE TITLE
Disable TimeInstant metadata

### ISSUE THREAD

**Issue by cbonillo** [telefonicaid/fiware-IoTAgent-Cplusplus#246]
I have configured a notification On Change. But if I resend two identically observations to IoTAgent (via SendObservation.py figway o via REST), two notifications are send by OCB. Context data are different because TimeInstant metadata have changed between these two requests.

Is it possible to disable automatic TimeInstant metadata insertion?

**Comment by agonlucas** [comment]
No. TimeInstant always is added. There are a reason for that (we know this reason is not shared): we believe a measure is a value at a moment (in IoTAgent context).
