### ISSUE TITLE
Service 'mongodbdata' configuration key 'restart' contains an invalid type, it should be a string

### ISSUE THREAD

**Issue by azhagthott** [telefonicaid/fiware-IoTAgent-Cplusplus#315]
francisco@tesla:~/docker$ docker-compose -f iota.yaml up -d iotacpp
Validation failed, reason(s):
Service 'mongodbdata' configuration key 'restart' contains an invalid type, it should be a string

Change this 

mongodbdata:
    image: mongo:2.6
    volumes:
        - /data/db
    restart: "no"
    command: /bin/echo "Data-only container for mongodb."

Is that OK ??

**Comment by dadivx** [comment]
We weren't seeing that particular error, but certainly it wasn't correct. Thanks for spotting this. 
The fix has been merged.
