### ISSUE TITLE
mqtt connection user

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-IoTAgent-Cplusplus#336]
We are testing the MQTT support of the IoTAgent-Cplusplus (from docker latest image).
We managed to setup the services and devices using the Provision API.

When testing with mosquito_pub/sub tools, we only manage to publish/subscribe to topics when using the `admin` user (which requires no crendentials !?) that is reserved to "esp" (we suppose its the name of the IoTAgent connecting to the Mosquitto broker) according to `/etc/iot/aclfile.mqtt`: 

```
#ESP user must be "admin"
user admin
topic #

#Pattern applied to all users.
pattern %u/#
```

When trying to publish or subscribe without providing any user info (`-u admin` to mosquitto_pub/sub), the MQTT allows the connection to establish but we do not receive any message (commands) nor our messages are transmitted to Orion CB.

This works :

```
mosquitto_pub -d -h $HOST  -u admin -t $API_KEY/thing1/temperature -m 26
```

but this fails (silently!) :

```
mosquitto_pub -d -h $HOST -t $API_KEY/thing1/temperature -m 26
```

We also find surprising that the MQTT broker accepts all anonymous connections by default (`allow_anonymous true` in `/etc/iot/mosquitto.conf`).
Can this be changed (in `/etc/iot/aclfile.mqtt` ?) to only accept connections from user which match the API-KEY ?

Thanks,

**Comment by marcc-orange** [comment]
Ok, I just found in the module.md the reference to -u API-KEY user... Should be also be mentioned in the MQTT protocol (https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus/blob/develop/doc/MQTT_protocol.md).

**Comment by marcc-orange** [comment]
The fact that I can connect from a remote client with admin and no password, and access all topics still looks like an issue... no ?

**Comment by dadivx** [comment]
Hi, 
Marc, there's already information about how to work with ACL file on MQTT Protocol:
https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus/blob/develop/doc/MQTT_protocol.md#configuring-acl-in-mosquitto

Regarding connecting with no password, this was on purpose as it's easier to get started. It is possible to enable password for all users, though. You can do this if you want to enable passwords:
1. Enable the line in the mosquitto config file that points to the password file. 
2. Create password for all your actors wanting to pub/sub on MQTT (including "admin"). There's a utility provided by mosquitto for doing so.
3. Locate the file "sensormqtt.xml" (typically /etc/iot ) and provide the aforementioned password. 
Then you should include "-p" with the password for all your tests with mosquitto_pub/sub. 

Bear in mind that ACL/authentication is provided by the broker (Mosquitto) you can tweak that to fit your needs. On top of that we just came up with the way to build the topic structure and prevent  users for subscribing/publishing on other's topics.

**Comment by marcc-orange** [comment]
thanks for the info !
