### ISSUE TITLE
mqtt: crash when publishing with a bad token in topic

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-IoTAgent-Cplusplus#346]
We get a systematic crash of the IoTAgentCplusplus when publishing with a bad token in topic.
# Command

```
mosquitto_pub -d -h URL  -u "GOOD_TOKEN" -t "BAD_TOKEN/myEdison/lux" -m 22
```
# Logs

```
time=2015-12-03T15:28:33,280.731UTC | lvl=ERROR | comp=iota:IoTPlatform | op=get_service_by_apiKey_bbdd | file=[140317051320064:rest_handle.cc:973] | msg=get_service_by_apiKey_bbdd no service for apikexxxxxxx
time=2015-12-03T15:28:33,281.370UTC | lvl=ERROR | comp=iota:IoTPlatform | op=add_info | file=[140317051320064:IotaMqttServiceImpl.cc:151] | msg=Configuration error for service: /iot/mqtt [Service by ApiKey: not found[xxxxxxx]]
time=2015-12-03T15:28:33,281.452UTC | lvl=ERROR | comp=iota:IoTPlatform | op=doPublishCB | file=[140317051320064:IotaMqttServiceImpl.cc:213] | msg=Configuration error : std::exception
```

**Comment by marcc-orange** [comment]
We are going to provide the IoTAgent as one of the main components of the FIWARE IoT stack for  our upcoming hackathons.

Do you recommend us to use an earlier tagged (stable ?) version of the IoTAgentCplusplus, or do you recommend using the latest build ? 

BTW, the docker images do not have tags for releases, this would be a nice to allow us to easily test previous releases...

Thanks.

**Comment by dadivx** [comment]
Marc, we have recently solved this issue. Try with latest build (1.3.0 + ) and let me know if it's still failing. 
Regarding Docker, we'll have a look at it.

**Comment by marcc-orange** [comment]
It fixes the crash. Thanks.
