### ISSUE TITLE
artifactory.hi.inet

### ISSUE THREAD

**Issue by jicarretero** [telefonicaid/fiware-IoTAgent-Cplusplus#83]
There are 2 URLs in document https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus/blob/develop/doc/deploy.md#1-setting-up-repositories which aren't valid:

* baseurl=http://artifactory.hi.inet/artifactory/simple/common/mongodb/x86_64/
* baseurl=http://artifactory.hi.inet/artifactory/simple/yum-puppet/x86_64/

The problem is that "artifactory.hi.inet" doesn't seem to be a public domain (no whois, no dig...)

**Comment by agonlucas** [comment]
Those URLs have been removed.
